### ISSUE TITLE
codemapper crashes on symbolic links

### ISSUE THREAD

**Issue by strfx** [thejff/codemapper#30]
Hi! Thank you for your work on codemapper - its a big help when working in unfamiliar codebases :-)

#### Description

codemapper crashes when symbolic links are present.

#### Steps to reproduce

Run codemapper on a directory with symbolic links:
```
# Create a new .ts file
$ echo "{}" > test.ts
$ codemapper -i . -d 
# ... OK

# Create a symbolic link
$ ln -s test.ts link-to-test.ts
$ codemapper -i . -d --verbose
```

Output (highlighted relevant parts)
```
[INFO]: Performing startup checks
[INFO]: Checking platform and looking for dot executable
[INFO]: Startup checks succeeded
[INFO]: CLI Input detected, beginning processing...
[INFO]: Initialising file walker...
[INFO]: Building structure from: /<% snip %>/test
[INFO]: Building structure from /<% snip %>/test
[INFO]: Getting files and folders at /<% snip %>/test
[INFO]: Checking if folder acceptable: codemapper
>> [INFO]: Checking if folder acceptable: link-to-test.ts
>> [INFO]: Folder is acceptable: link-to-test.ts
[INFO]: Checking if file acceptable: test.ts
[INFO]: File is acceptable: test.ts
[INFO]: Directory structure: 
{
    "files": [
        "test.ts"
    ],
>>    "folders": [
>>        "link-to-test.ts"
>>    ]
}
[INFO]: Building structure from /<% snip %>/test/link-to-test.ts
[INFO]: Getting files and folders at /<% snip %>/test/link-to-test.ts
[ERROR]: An error occured during mapping!
>> [ERROR]: Error: ENOTDIR: not a directory, scandir '/<% snip %>/test/link-to-test.ts'
[WARNING]: Process did not finish correctly
```

The verbose output pretty much sums it up: codemapper treats the symlink `link-to-test.ts` as a directory, crashes when attempting to resolving the directory.

#### Next steps

How do you want to handle symbolic links in general? You could provide a CLI option to let users decide whether to follow symbolic links or to ignore them.

Let me know what you think, I'll be happy to send a PR your way

**Comment by Chris-Holdt** [comment]
Hi @strfx,

I'm glad to hear that you have been finding codemapper useful! 

Thanks for reporting this issue, my codebases don't tend to use symlinks so I hadn't realised that this needed to be considered.
I've just been having a look at the code to see what was happening and have put together a fix for it that checks if a file is a symlink, and then does a follow up check to see if it links to a folder or a file. 
Using the steps you provided above to check, this does resolve the issue.

As you suggested, I think it is worthwhile having a flag that allows users to ignore symlinks, I am also adding this in. This defaults to false (as in the default will be that they are not ignored).

I'm just finishing up the changes and making sure the exclude symlinks flag works correctly, once I'm happy with that I will push the changes to a new branch and would be grateful if you could test it and confirm that it all works correctly for your usecase.

If you have any other suggestions or improvements based on your usage I am more than happy for you to share them!

**Comment by Chris-Holdt** [comment]
Hi @strfx,

I have pushed the fix, for local testing there isn't anything special needed, just:
```sh
npm i

npm run build

node ./lib/index.js <CLI Args>
```

I have added the ability to exclude the symlinks as `-exS` and `--excludeSymlinks`

Let me know how it goes!

**Comment by strfx** [comment]
@Chris-Holdt works like a charm! :sparkles: Thank you for that fast fix :-)

**Comment by Chris-Holdt** [comment]
@strfx The fix has been publish on NPM now fyi
